### ISSUE TITLE
New feature: builds for structured conf without target

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#108]
## Pitch

There have been times where I want to use `builds` to make a structured config that *doesn't* have a target. There may be a relatively clean way to enable this, namely by providing a `NOTHING` (would like ideas for potentially better names) object, so that:

```python
from hydra_zen import NOTHING, builds
Conf = builds(NOTHING, a=1, b="hi")
```

is equivalent to

```python
@dataclass
class Conf:
    a : Any = 1
    b : Any = "hi"
```

```python
>>> print(to_yaml(conf))  # look, Ma, no _target_!
a: 1
b: hi
```
**Note: Definitely check out the "Alternatives" section; now that I have written it out, it feels like it might be preferable**

### Brevity / Leveraging Power of `builds`
Not only is this more succinct (it is really nice to not have to specify annotations when you don't care about them), but it enables us to leverage the nice automation built into `builds`, e.g. it takes care of wrapping mutable values with default-factories. Thus things get to be even _more_ succinct!

```python
@dataclass
class Config:
    defaults: List[Any] = field(default_factory=lambda: list([dict(db="mysql")]))
    db : Any = MISSING
```

becomes

```python
Conf = builds(NOTHING, defaults=[dict(db="mysql")], db=MISSING)
```

### It's Newbie-friendly / Top-level annotations are often a lost-cause

This doesn't work, and it [will likely never work](https://github.com/facebookresearch/hydra/issues/1759)

```python
def returns_int() -> int:
    return 1

@dataclass
class Config:
    x:  int = builds(returns_int)  # raises ValidationError: Builds_returnsint is not a subclass of int
```

the advice from omry here (understandably) is "just use `Any`", which is precisely what `builds(NOTHING, x=builds(returns_int))` will do. Thus new users who go this route would not even need to know that they are avoiding this type-validation situation, whereas writing a dataclass explicitly will naturally have them thinking "well what *is* the right annotation here, anyway"?

## Seeing this in action

```python
from hydra.conf import ConfigStore
from hydra_zen import MISSING
from hydra_zen.experimental import hydra_run

Conf = builds(NOTHING, defaults=[dict(db="mysql")], db=MISSING)

cs = ConfigStore.instance()
cs.store(group="db", name="mysql", node=builds(dict, a=1))
cs.store(group="db", name="postgresql", node=builds(dict, a=2))
```

```python
>>> hydra_run(conf, instantiate).return_value
{'db': {'a': 1}}
```

```python
>>> hydra_run(conf, instantiate, overrides=["db=postgresql"]).return_value
{'db': {'a': 2}}
```

## Implementation details
Invoking zen-processing on `NOTHING` will always raise. E.g. 

```python
>>> builds(NOTHING, a=2, hydra_partial=True)  # raises
>>> builds(NOTHING, a=2, hydra_meta=dict(b=2))  # raises
```

Specifying positional arguments is not allowed

```python
>>> builds(NOTHING, "hi")  # raises
```

In terms of type-annotations, this special case will be overloaded as:

```python
builds(NOTHING)  # type: Type[Builds[Type[DictConfig]]]
```

since

```python
>>> type(instantiate(builds(NOTHING)))
omegaconf.dictconfig.DictConfig
```

## Alternatives

Another option would be providing a new function, 

```python
def make_config(
    *,
    hydra_recursive=None,
    hydra_convert=None,
    frozen=False,
    dataclass_name=None,
    config_bases=(),
    **fields
):
    ...
```
which would basically call `builds(NOTHING, ...)` under the hood. The benefits of this are 
- People don't need to worry about passing around `NOTHING`; `config(a=1, b=2)` is cleaner than `builds(NOTHING, a=1, b=2)`
- We can exclusively expose the hydra options that are valid (e.g. they don't even have the *option* of using `hydra_partial`)
- `builds`'s docstring doesn't suffer the burden of having to document the `NOTHING` use case.
- This does give us the potential for exposing non-targeted-conf-specific options, e.g. controlling [default-list composition order](https://hydra.cc/docs/tutorials/structured_config/defaults#a-note-about-composition-order) without cluttering `builds`

## Feedback

- Is the motivation for this substantial enough that this feature is warranted? 
- If we go with `make_config`, is that a good name? Is it distinct enough from `builds`?
- Are there any opportunities or downsides that I am missing here?

**Comment by jgbos** [comment]
I've been debating bringing this up.  I wasn't sure if it would be confusing to allow `builds` to have an empty target, but I really like  your solution.  I should always remember where there's a will there's a way :)

Another use case:  build a base config without a target that other configurations can extend via `builds_base` (maybe it's a like a protocol).  When I first started using Hydra this is something I did, not sure I've really come across the need with `builds` though.  I bring this up mostly as something to consider for naming.  Is `make_config` good here?  Is there an "actiony" word like `builds`?

Lets do this though!

**Comment by rsokl** [comment]
> I've been debating bringing this up

Awesome! I glad that this came up organically for you as well - it seems like it'll be a useful thing to have. With my docs-hat on, I realize we can do all of our intro tutorials without even mentioning dataclasses!

> `make_config` good here
This is the best I can come up with for the time-being, but I am very open to other ideas and will continue brainstorming. I'll start the PR with `make_config`, but that doesn't mean we are married to it..until it gets released publicly at least!

**Comment by rsokl** [comment]
`configures` would be kind of cool:

```python
configures(model=builds(Classifier), optim=builds(Adam))
```

But I think it is too easy to confuse `configures` and `builds`.. `configures(Adam, lr=0.5)` is too sensible.

**Comment by jgbos** [comment]
The issue with using "configures" is that it doesn't create a Hydra Structured Config, just a Dataclass containing configs the experiment.  `make_config` is probably less confusing than any other option.
