### ISSUE TITLE
Merging and moving hydra_run and hydra_multirun

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#127]
@jgbos  I [agree](https://github.com/mit-ll-responsible-ai/hydra-zen/pull/126#issuecomment-938291183) that we should get rid of `hydra_zen.experimental`. A couple of thoughts.

1. Is there any reason why we can't simply merge `hydra_run` and `hydra_multirun` into one function: `hydra_run`? They have identical interfaces. We can simply expose the option `hydra_run(..., multirun=True)`; this would have a similar feel to using the `--multirun` CLI option.
2. Regardless of where we actually put this in the code base, I propose that we expose this at the top-level of hydra-zen. E.g. imports become `from hydra_zen import hydra_run`

We could pretty easily make this change and deprecate all imports from `hydra_zen.experimental`.

Part of me wonders if we are making too many now-this-is-deprecated changes in one release. That being said, if I am going to go update my old hydra-zen code, I don't want to have to go back a month later and make *more* changes.

Thoughts?

**Comment by jgbos** [comment]
Agreed.  How about `launch` or `execute`? Oh, or just `hydra`?  I'd be ok sticking with `hydra_run` though.

**Comment by rsokl** [comment]
Closed by #131
