### ISSUE TITLE
Adding a citation file & submitting to JOSS

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#145]
GitHub has integration for making a repo citeable: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Also, I would like to submit to the [Journal of Open Source Software](https://www.google.com/search?client=firefox-b-1-e&q=joss+journal) at some point.

**Comment by rsokl** [comment]
Our [responsible AI paper](https://github.com/HypothesisWorks/hypothesis/issues/3379) is a better thing to cite

**Comment by Jasha10** [comment]
> Our [responsible AI paper](https://github.com/HypothesisWorks/hypothesis/issues/3379) is a better thing to cite

^ Is that link pointing to the right place? It doesn't look like a paper to me :P
