### ISSUE TITLE
Make a note about `defaults`  in our config-groups tutorial

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#147]
Working through [this](https://mit-ll-responsible-ai.github.io/hydra-zen/tutorials/config_groups.html) tutorial has the user configure a `defaults` field:

```python
Config = make_config("player", defaults=["_self_", {"player": "base"}])
```

a reader might naturally look to `make_config`'s docs for explanation...but there is none since we don't give that field any special treatment in `make_config`. We should at least add a callout box in the tutorial that directs them, loud and clear, to the appropriate Hydra docs.

We also might consider:
- Mentioning is in the Notes section of make_config
- Actually including `defaults` or maybe `hydra_defaults` as a reserved field in `make_config` and thus document it... but I don't really see utility in that.

**Comment by jgbos** [comment]
Yeah, I see why we might not want to completely tie this to Hydra, but at the same time it will lead to errors when running `launch` or CLI.  Unfortunately the swappable configs and the `ConfigStore` are very much Hydra centric but not very user friendly.

**Comment by rsokl** [comment]
> it will lead to errors when running launch or CLI

That's a good point in favor of adding in the reference docs for `make_config` that `defaults` has special meaning for Hydra... perhaps it is worth having as its own parameter. Definitely something for us to mull over.
