### ISSUE TITLE
Complex Numbers

### ISSUE THREAD

**Issue by jgbos** [mit-ll-responsible-ai/hydra-zen#149]
So `builds` supports instantiating complex numbers:

```python
builds(list, [1 + 1j])
#or
builds(torch.tensor, 1+1j)
```

but omegaconf does not support serializing to yaml:

```python
to_yaml(builds(list, [1+1j])
```
leads to the following error
```
UnsupportedValueType: Value 'complex' is not a supported primitive type
    full_key: _args_[0][0]
    object_type=list
```

I'm not sure if we can add support for this, but should at least be documented.

**Comment by rsokl** [comment]
### A solution that can be used right now

A somewhat clean way to do this is make a config class for `complex` and a helper function just for making your code more concise:

```python
>>> ComplexConf = builds(complex, populate_full_signature=True)

>>> def c(z: complex):
...     return ComplexConf(real=z.real, imag=z.imag)

>>> Conf = builds(list, [c(1 + 1j), c(-2 + 10j)])
>>> instantiate(Conf)
[(1+1j), (-2+10j)]

>>> print(to_yaml(Conf))
_target_: builtins.list
_args_:
- - _target_: builtins.complex
    real: 1.0
    imag: 1.0
  - _target_: builtins.complex
    real: -2.0
    imag: 10.0
```

### Handling this internally

We could handle this – to an extent – on our end via the same mechanism where we auto-wrap things in `just` where need-be:

https://github.com/mit-ll-responsible-ai/hydra-zen/blob/871d8a28f03e1c4b949ba33c9c8ce9a6e3037988/src/hydra_zen/structured_configs/_implementations.py#L488-L496

That being said, this would not handle complex-values in lists. We also could traverse lists to make this conversion, but I get a bit worried about performance there.

I suspect that using complex values in configs is a relatively rare use case, so it might not be worth it for us to build in "auto" support for it. Let me you think the first suggestion that I made is sufficient. 

This would probably make for a good How To? "How to configure primitives not supported by Hydra".

**Comment by rsokl** [comment]
> but should at least be documented

A few things that we can / should do:
- Include, somewhere in our reference docs, a list of Hydra's supported primitives
- Improve the type-annotations on `builds` so that passing raw complex numbers will get the IDE to warn you

**Comment by rsokl** [comment]
I have been thinking more about this, and more and more. Now my opinion is that hydra-zen should make primitives like `complex`, `set`, and `Path` "just work". It seems to me  that this is another piece of low-hanging fruit where hydra-zen can smooth out yet another sharp edge of using Hydra.
