### ISSUE TITLE
Improving our internal code organization for handling cross-version compatibility

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#183]
Issues #172 , #181, and #182 all pertain to fixes/capabilities being introduced to omegaconf/Hydra that we already support. Thus we need to adaptively defer to upstream support for these capabilities when users have sufficiently-new version of omageconf/Hydra installed. 

Currently, we don't really have any tooling for making this process particularly centralized or simple. It would be good to have any fields, functions, and other objects that need be set dynamically based on omegaconf/Hydra versions all live in a common place.

Additionally, we should improve our CI to test against master branches of Hydra and omegaconf, since those projects don't seem to be pushing dev versions to pypi lately.

**Comment by jgbos** [comment]
Interesting, do you have an outline or example of how we go about centralizing this?

**Comment by rsokl** [comment]
I am thinking of having `hydra_zen._compatibility` (not public-facing), which is responsible for checking the present omegaconf and Hydra versions, and then set values and populate collections appropriately. 

E.g. in it we would set the variable `HYDRA_SUPPORTS_PARTIAL`, which we would then reference in `hydra_zen.structured_configs._implementations` to determine whether or not we defer to Hydra to support partial configs. Similarly, we would set `PATCH_OMEGACONF_830` there, update `HYDRA_SUPPORTED_PRIMITIVES`, etc.

The goal of this is that there is a single location where we define all of the omegaconf/Hydra-specific behaviors that are version-dependent. Hopefully this will help us keep track of all such behaviors. Currently, these things are scattered throughout our internals with no rhyme or reason.

**Comment by rsokl** [comment]
Installing Hydra from source [requires Java](https://github.com/facebookresearch/hydra/issues/1232#issuecomment-750378099), thus we cannot easily test against main without building wheels ourselves.

There is an issue tracking nightly builds for Hydra here: https://github.com/facebookresearch/hydra/issues/1112
