### ISSUE TITLE
hydra-zen unable to extend hydra-zen functionality for base builder classes since at least version 0.7

### ISSUE THREAD

**Issue by mgrinshpon-doxel** [mit-ll-responsible-ai/hydra-zen#288]
Note: this worked fine in hydra-zen =< v0.5 and is a follow-on from this conversion: https://github.com/mit-ll-responsible-ai/hydra-zen/issues/284#issuecomment-1159009054

Let's say I wanted to make a torch optimizer and a bunch of its children:

```python
BuildsOptimizer = builds(torch.optim.Optimizer, zen_partial=True)
BuildsSGD = builds(
    torch.optim.SGD, 
    populate_full_signature=True,
    zen_partial=True,
    zen_meta={"optimizer": "SGD"},
    builds_bases=(BuildsOptimizer,),
)
ConfigStore.instance().store(...
```
This will fail to compile with the warning that hydra-zen functionality cannot be extended. Instead, `BuildsOptimizer` would have to look like this:
```python
BuildsOptimizer = builds(torch.optim.Optimizer)
BuildsSGD = ...
```

However, if I want type hinting in my `hydra_zen.ZenField` that explains how the field should be used, I'd do like this:
```python
optimizer_field = ZenField(name="optimizer", hint=BuildsOptimizer)
optimizer_default = [{"optimizer": "really_good_optimizer"}]
```
This feels in-congruent since my hint now no-longer explains that everything here really ought to be built with a partial- the base class requires the model weights and the model weights won't be known until runtime. The partial is really part of the abstraction of the base class and not an implementation detail of any of my optimizers.

P.S. love this library. Y'all rock!

**Comment by rsokl** [comment]
I currently have a WIP PR at #290 where all restrictions involving inheritance, zen-meta, zen-partial are removed. It looks like all of the major potential pitfalls (e.g. getting annotations right) have been cleared. But I will need to take some time to ensure that there are no nasty unintended consequences.

**Comment by rsokl** [comment]
@mgrinshpon-doxel  just FYI - this restriction on partial config inheritance has been lifted. I will publish a release candidate for `v0.8.0` so that you can try out at your leisure. Apologies for the delay -- I was unable to work on hydra-zen for an extended period of time

**Comment by rsokl** [comment]
A release candidate for `v0.8.0` is now available on PyPI: https://pypi.org/project/hydra-zen/0.8.0rc1/

**Comment by rsokl** [comment]
@mgrinshpon-doxel  FYI: `v0.8.0` has been released
