### ISSUE TITLE
How to resolve a config without instantiating?

### ISSUE THREAD

**Issue by konradkalita** [mit-ll-responsible-ai/hydra-zen#312]
Hi. I use hydra and I consider switching to hydra-zen but I have a specific use-case I am not sure how to solve. In my current setup I want to first resolve all configs (fill string interpolation etc) but without instantiating target classes in order to save this config as pickle for reproducibility. Currently I use [OmegaConf.to_object](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#omegaconf-to-object) method for it but when I tried to test it with hydra-zen classes it throws a type check error:
```
instance of Builds_Transformation, tuple or dict expected (type=type_error.dataclass; class_name=Builds_Transformation)
```

Are you aware of some method of doing this config resolution in hydra-zen?

**Comment by rsokl** [comment]
I can confirm that `to_object` doesn't work on dataclass types (which is what `builds` creates), but I wasn't able to reproduce that particular error message. So I am not 100% sure that I am replicating your use case here.

That being said. Using [OmegaConf.structured](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#from-structured-config) and [OmegaConf.resolve](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#omegaconf-resolve) should do the trick:

```python
from omegaconf import OmegaConf, DictConfig

from hydra_zen import builds

class A:
    def __init__(self, x, y):
        self.x = x
        self.y = y

Conf = builds(A, x=1, y="${x}")

Conf = OmegaConf.structured(Conf)
OmegaConf.resolve(Conf)

print(Conf)
# prints:
# {'_target_': '__main__.A', 'x': 1, 'y': 1}
```

Does this suit your usecase?

**Comment by konradkalita** [comment]
Yes, it did a trick. I had a problem that dataclasses `builds` creates are not picklable by stdlib implementation but I solved by switching to cloudpickle lib. Thank you a lot. 

Actually I have 1 more question. For example like that:
```python
class Bar:
    pass
class Foo:
    __init__(self, bar: Bar):
        self.bar = bar
```
To make it configurable I do:
```python
BarConf = builds(Bar)
FooConf = builds(Foo, bar = BarConf)
```

Now what I should do if bar should be optional field for `Foo` to make it configurable still? (In hydra I used structured configs)
```python
class Foo:
    __init__(self, bar: Optional[Bar] = None):
        self.bar = bar
FooConfg = builds(Foo, bar = ???)
```

**Comment by rsokl** [comment]
> Yes, it did a trick.

Great!

> Now what I should do if bar should be optional field for Foo to make it configurable still?

I'm not sure that I fully follow, but perhaps this addresses your question:

```python
FooConfg = builds(Foo, populate_full_signature=True)
# which, in this case, is equivalent to: FooConfg = builds(Foo, bar=None)
```

This would be equivalent to:

```python
@dataclass
class FooConfg:
    _target_: str = "path.to.Foo"
    bar : Optional[Bar] = None
```

`FooConfg.bar` will default to `None`, but still can be configured/overridden when you launch your app.

> In hydra I used structured configs

Any solution you used in Hydra with structured configs should work here as well, since hydra-zen is simply creating dataclass types that adhere to the structured config schema. E.g., you can pass in `MISSING` to `bar`

**Comment by konradkalita** [comment]
Yes. you're right. I must have misinterpreted some example. Thank you again.

**Comment by rsokl** [comment]
My pleasure!
