### ISSUE TITLE
`config_path` broken for `hydra_main`

### ISSUE THREAD

**Issue by petosa** [mit-ll-responsible-ai/hydra-zen#381]
Hello, it seems like `config_path` is not functional when used with the new `@zen` + `hydra_main` pattern introduced in 0.9.0.

Here's how I repro:

File `/home/petosa/repro/config.yaml`
```
db:
  host: local
  port: 3307
```
File `/home/petosa/repro/zen.py`
```
from hydra_zen import zen

@zen
def main(zen_cfg):
    print(zen_cfg)

if __name__ == "__main__":
    main.hydra_main(config_name="conf", verion_base="1.1", config_path="/home/petosa/repro")
```

File `/home/petosa/repro/hy.py`
```
import hydra

@hydra.main(config_name="conf", verion_base="1.1", config_path="/home/petosa/repro")
def main(cfg):
    print(cfg)

if __name__ == "__main__":
    main()

```

Running `hy.py` successfully loads and prints the config.

Running `zen.py` gives exception 
`Primary config module 'hydra_zen.wrapper..home.petosa.repro' not found.`

**Comment by rsokl** [comment]
That's odd.. I am unable to reproduce the error based on your example. I fixed a couple of typos in your example:
- `verion_base` -> `version_base`
- `"conf"` -> `"config"`  (based on the fact that you state that your config is at the path `/home/petosa/repro/config.yaml`)

Here is my example:

```
dir/
  |- bug_main.py
  |- config.yaml
```

With `config.yaml`:

```
db:
  host: local
  port: 3307
```

and `bug_main.yml`:

```python
# contents of bug_main.py

from pathlib import Path

from hydra_zen import zen

cwd = Path.cwd()


@zen
def main(zen_cfg):
    print(zen_cfg)


if __name__ == "__main__":
    main.hydra_main(
        config_name="config", version_base="1.1", config_path=str(cwd)
    )
```

Running the script gives me the expected result:

```console
$ python bug_main.py
C:\Users\rsokl\miniconda3\envs\hydra-zen\lib\site-packages\hydra\_internal\hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
{'db': {'host': 'local', 'port': 3307}}
```

As you can see, [the logic for passing config_path to hydra.main](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/746d5fe470c38bca4e9398e884b012cc9a16e6ce/src/hydra_zen/wrapper/_implementations.py#L395-L405) is pretty straightforward, so there isn't too much opportunity for error here.

Please let me know if I have missed something or if the issue persists!

**Comment by petosa** [comment]
Strange, let me try reproducing in a clean environment.

**Comment by petosa** [comment]
I figured it out, this issue can be reproduced if I downgrade hydra to `1.2.0`. Upgrading to `1.3.1` fixed the issue. Thanks for your help - there is no intent to support that older version of hydra right? (Not a requirement for me, but wanted to check the intended backwards compatibility).

**Comment by rsokl** [comment]
Ah! Thanks for figuring this out. It seems to be linked to [this issue](https://github.com/facebookresearch/hydra/pull/2303).

> there is no intent to support that older version of hydra right?

I do intend to support older versions of Hydra. I will see if I can patch `zen` to be backwards compatible with Hydra. Thanks for this report!

**Comment by rsokl** [comment]
Thanks again for bringing this issue to my attention. Unfortunately I was only able to ensure that relative `config_path` entries behave properly via `zen` for Hydra 1.3.0+. Otherwise hydra-zen will warn users. These changes are in v0.9.1, which will be released momentarily.
