### ISSUE TITLE
Mypy errors with hydrated_dataclass

### ISSUE THREAD

**Issue by jzazo** [mit-ll-responsible-ai/hydra-zen#420]
Hi. The following code from your documentation raises a mypy error (without the frozen argument):

```python
@hydrated_dataclass(target=dict)
class DictConf:
    x: int = 2
    y: str = 'hello'

DictConf(x=10)  #  mypy[call-arg] Unexpected keyword argument "x" for "DictConf"
```

**Comment by rsokl** [comment]
mypy doesn't support dataclass transforms yet: https://github.com/python/mypy/issues/14293 . We develop against pyright for our support for static analysis as it is much faster (on the order of *years*) to implement new typing features.
