### ISSUE TITLE
Question: Compose API

### ISSUE THREAD

**Issue by jzazo** [mit-ll-responsible-ai/hydra-zen#421]
Hi. Is there a way to tell `launch` (or another mechanism) to specify a `conf_dir` where to find YAML files? Does hydra_zen support loading YAML files? Should I be using hydra's Compose API instead? Thanks!

**Comment by jgbos** [comment]
No, `launch` is not setup to support yaml files.  I don't think there's anything preventing an update to allow that support though.

You might be able to first load in the config using the Compose API and then run `launch` with the loaded `DictConfig`.

**Comment by jzazo** [comment]
I think it's not working well. I tried to register my dataclass configs using then `ZenStore`, then run `store.add_to_hydra_store()`. Then use the compose API, but the `DictConfig` I get does not have access to the configs that I register to the `ZenStore`.
Everything works if I use hydra's `ConfigStore`.

**Comment by rsokl** [comment]
> Everything works if I use hydra's ConfigStore.

I don't see how there could be a discrepancy. `store.add_to_hydra_store()` just [calls hydra's ConfigStore under the hood](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/374c013f34d397b6293d6f75d3936016e79cc6d6/src/hydra_zen/wrapper/_implementations.py#L1594-L1617).

**Comment by rsokl** [comment]
When add a config to `ZenStore` could you specify `to_config=lambda x: x` to ensure there isn't any auto-config behavior that is messing with the compose API here? When you do this, using zen store should be effectively identical to using hydra's store.

**Comment by jzazo** [comment]
It didn't help. I am not sure what I may be doing wrong:
```python
from dataclasses import dataclass
from pathlib import Path
from hydra import compose, initialize_config_dir
from hydra_zen import ZenStore, to_yaml

CONF_PATH = Path("src/resources/conf")  # not really used for anything yet

@dataclass
class Config:
    foo: int = 1

store = ZenStore()
store(name="config", node=Config, to_config=lambda x: x)
store.add_to_hydra_store()

if __name__ == "__main__":
    with initialize_config_dir(config_dir=str(CONF_PATH.absolute()), job_name="example"):
        cfg = compose(config_name="config")
        print(to_yaml(cfg))
```

**Comment by rsokl** [comment]
Thanks for trying this. I can reproduce this on my end. I'll get to the bottom of this!

**Comment by rsokl** [comment]
Ah, there is an error in your call to `ZenStore` - it doesn't use `node` as a kwarg:

```python
store = ZenStore()
store(Config, name="bar", to_config=lambda x: x)
```

If I call 

```python
CONF_PATH = Path("./conf")  # not really used for anything yet


@dataclass
class Config:
    foo: int = 1


store = ZenStore()
store(Config, name="bar", to_config=lambda x: x)

store.add_to_hydra_store()

with initialize_config_dir(
    config_dir=str(CONF_PATH.absolute()), job_name="example", version_base="1.3"
):
    cfg = compose(config_name="bar")
    print(to_yaml(cfg))
```
I get:
```
foo: 1
```
as expected.

I might add a check to `ZenStore` that warns users on suspicious use of the `node` kwarg.

**Comment by jzazo** [comment]
Thanks for the feedback, I tried and worked for me. Maybe consider adding support to using `launch` with `config_dir` as well?

**Comment by rsokl** [comment]
Unfortunately I don't think I'll have time to add support for this in the near future. That being said, I would be happy to provide feedback on a PR :)

**Comment by cswartzvi** [comment]
@rsokl sorry to dig up an old issue - would you still be willing to provide feedback on a community PR that added `config_dir` (or `config_path`) to `launch`?
