### ISSUE TITLE
Nested Partial Builds not Converted when Using Stores and Hydrated_dataclass with Zen_partial

### ISSUE THREAD

**Issue by mauricekraus** [mit-ll-responsible-ai/hydra-zen#453]
When using stores and hydrated_dataclass together with zen_partial, it seems that the _target_ field gets assigned the Config instead of the actual target. This results in functools.partial[<class '__main__.NestedModelConf'>] instead of functools.partial[<class '__main__.NestedModel'>]. However, NestedModel is also a partial, which results in a double partial, and the need for manually initializing the config in the outer model.

```python
from dataclasses import dataclass, field
from hydra_zen import (
    MISSING,
    hydrated_dataclass,
    instantiate,
    zen,
    store,
)
from hydra_zen.typing import Partial
from omegaconf import DictConfig, OmegaConf
from hydra.core.config_store import ConfigStore
from torch import nn


class NestedModel(nn.Module):
    def __init__(self, **kwargs):
        super().__init__()
        params = NestedModelConf(**kwargs)
        self.linear = nn.Linear(params.in_features, 10)

    def forward(self, x):
        return self.linear(x)


class Model(nn.Module):
    def __init__(self, **kwargs):
        super().__init__()
        params = ModelConf(**kwargs)
        self.linear = nn.Linear(params.in_features, params.out_features)
        self.nested = params.nested(params.out_features)

    def forward(self, x):
        return self.linear(x)


@store(name="x", group="model/layer")
@hydrated_dataclass(NestedModel, zen_partial=True)
class NestedModelConf:
    in_features: int = MISSING


@hydrated_dataclass(nn.Module)
class BaseModelConf:
    pass


@store(name="mod", group="model", in_features=10, out_features=20)
@hydrated_dataclass(Model)
class ModelConf(BaseModelConf):
    in_features: int = 1
    out_features: int = 1
    nested: Partial[NestedModel] = MISSING


def task(zen_cfg: DictConfig):
    cfg: Exp = instantiate(zen_cfg)
    print(cfg.x + cfg.y)
    model = instantiate(cfg.model)


@dataclass
class Exp:
    x: int
    y: int
    model: BaseModelConf


cs = ConfigStore.instance()
cs.store(name="my_app", node=Exp)

@store(name=lambda cfg: cfg.__name__, group="exp", package="_global_")
@dataclass
class OverrideExp(Exp):
    x: int = 52
    y: int = 30
    model: BaseModelConf = MISSING
    defaults: list = field(
        default_factory=lambda: [
            "_self_",
            {
                "/model": "mod",
            },
            {
                "/model/layer@model.nested": "x",
            },
        ]
    )


if __name__ == "__main__":
    store.add_to_hydra_store()
    zen(task).hydra_main(config_name="my_app", config_path=None, version_base="1.3")
```

The line `self.nested = params.nested(params.out_features)` is not valid, as it simply returns NestedModelConf(in_features=20, _target_='__main__.NestedModel', _partial_=True). In order to get the actual target, I have to execute instantiate(self.nested). This will give me functools.partial(<class '__main__.NestedModel'>, in_features=20), which again I have to call.

I hope this makes sense and that I used the library correctly.

To run this code, I executed: python main.py +exp=OverrideExp

For completion's sake, this is the produced job YAML:

```yaml
x: 52
'y': 30
model:
  _target_: __main__.ModelConf
  in_features: 10
  out_features: 20
  nested:
    in_features: ???
    _target_: __main__.NestedModelConf
    _partial_: true
_target_: __main__.OverrideExp
```
For now I resolved the problem by applying this function to the task config: 

```python
def fix_partials(cfg: DictConfig):
    for k, v in cfg.items():
        if isinstance(v, DictConfig):
            if "_partial_" in v:
                v._target_ = v._target_.replace("Conf", "")
                return cfg
            cfg[k] = fix_partials(v)

    return cfg 
```

However, this is a rather hacky solution and requires exact naming.

A few additional notes:
```python
@dataclass
class Exp:
    x: int
    y: int
    model: BaseModelConf


cs = ConfigStore.instance()
cs.store(name="my_app", node=Exp)
```
is required, because If I use the builtin hydra_zen store on either the task or this base experiment, OmegaConf, cannot merge any subclass Experiment with this one. Apparently `Builds_Exp` and `Builds_OverrideExp` are not of the same base type.

Thank you for your help.

**Comment by rsokl** [comment]
Thanks for the detailed write up. The issue stems from [store's](https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.ZenStore.html) auto-config support mishandling `hydrated_dataclass` inputs.

I have a fix / enhancement in the works that will be included in 0.11.0. I'll let you know when the pre-release has the fix so that you can verify that it resolves your issue. 

In the meantime, you can proceed by disabling store's auto-config behavior when you are decorating hydrated dataclasses. You can do this via:

```python
hstore = store(to_config=lambda x: x)
```

and then use `hstore` to decorate your hydrated dataclasses.

**Comment by mauricekraus** [comment]
Okay thank you! This works. However, when i understand it correctly, it only works for "dumb" store annotations right?

e.g.

```python
@hstore(name="x", group="model/layer")
@hydrated_dataclass(NestedModel, zen_partial=True)
class NestedModelConf:
    in_features: int = MISSING
```
works without any configuration, but 

```python
@hstore(name="mod2", group="model", in_features=15, out_features=20)
@hstore(name="mod", group="model", in_features=10, out_features=20)
@hydrated_dataclass(Model)
class ModelConf(BaseModelConf):
    in_features: int = 1
    out_features: int = 1
    nested: Partial[NestedModel] = MISSING
```

doesn't.
Nevertheless, this is fine for me.

I'll watch over the issue and will test your fix when its ready. Thanks again!

**Comment by rsokl** [comment]
The fix is in v0.11.0rc3, which you can give a whirl with `pip install --pre hydra-zen`

**Comment by rsokl** [comment]
Please let me know if this does/doesn't fix your issue!

**Comment by mauricekraus** [comment]
@rsokl Thank you this indeed fixes my issue!
