### ISSUE TITLE
Inconsistent handling of constructor default values in Hydra-Zen

### ISSUE THREAD

**Issue by Sstrap** [mit-ll-responsible-ai/hydra-zen#549]
# Description

I've observed that the behavior of Hydra-Zen varies depending on the type of arguments with default values in class constructors.

## Code sample
```
import hydra_zen as zen

class Class1():
    def __init__(self, a: int=None):
        self.a = a

class Class2():
    def __init__(self, a: dict=None):
        self.a = a
```
Now calling `zen.instantiate(zen.builds(Class2, populate_full_signature=True))` will return an (expected) error:
```
ValidationError: field 'a' is not Optional
    full_key: a
    reference_type=Dict[Any, Any]
    object_type=NoneType
```

But  `zen.instantiate(zen.builds(Class1, populate_full_signature=True))` does not raise any error. It is actually the same if type is `str.

Is it a wanted behaviour ?

# Environment
I am running hydra_zen=0.11.0 on python 3.11

**Comment by rsokl** [comment]
I can't reproduce this

![image](https://github.com/mit-ll-responsible-ai/hydra-zen/assets/29104956/05ea9d5a-4811-491d-b66c-4f9210807142)

**Comment by rsokl** [comment]
what version of Hydra are you using?

**Comment by rsokl** [comment]
Regardless, the most straightforward solution is to use the `Optional[...]` annotation when you want to specify `None` as a default.

Feel free to reopen if there is a more fundamental issue here.

**Comment by Sstrap** [comment]
Thanks for your feedback @rsokl ! I'm using hydra 0.11.0.
Actually I notice that the error is raised with omegaconf 2.2.1 (that was used in my example) but not with omegaconf 2.3.0.

Now behaviour is consistent :). But, since I set `populate_full_signature` is set to `True` and the typing is incorrect I would expect an error to be raised, maybe there is something I'm missing.
