### ISSUE TITLE
How to create new instance of ConfigStore

### ISSUE THREAD

**Issue by thomassajot** [mit-ll-responsible-ai/hydra-zen#581]
Is it possible to instantiate a new empty `ConfigStore` object? 
Unfortunately, the dependency of the project requires that the other existing ConfigStore is pulled in which pollutes the new store.

**Comment by jgbos** [comment]
Great question @thomassajot.  I think the answer is yes, but it depends on how you use it.

You can create a new hydra-zen store via 

```python
import hydra_zen as hz

my_store = hz.ZenStore(name="my custom store")
my_store(hz.make_config(foo=1), group="my_group", name="config_name")
```

The catch is when you want to add the configs to the Hydra `ConfigStore`:

```python
my_store.add_to_hydra_store()
```

I believe the current behavior will raise an error if the config group and name exist in the Hydra `ConfigStore`.  If you want to overwrite the store entries you can do:

```python
my_store.add_to_hydra_store(overwrite_ok=True)
```

**Comment by thomassajot** [comment]
Thanks for your reply, 
However, the new set of config uses the same group names as the first one, but does not overwrite necessarily all the names that exists already, hence the old config are still available but not compatible with the functions in the new store.

Here is what the example looks like

Original config file
```python
cs = ConfigStore.instance()
# datamodules
cs.store(group="datamodule", name="heuristic", node=heuristic_datamodule_cfg)
cs.store(group="datamodule", name="auto", node=auto_datamodule_cfg)
# models
cs.store(group="model", name="mlp", node=mlp_cfg)
cs.store(group="model", name="resnet", node=resnet_cfg)
# training
cs.store(node=TrainCfg, name="base", package="_global_")
cs.store(group="mode", name="train_C1T1", node=TrainC1T1Cfg, package="_global_")
```
Where `TrainCfg` takes in a `datamodule` and `model` argument.

`main.py` which depends on the **original** config file.
```python
...
if __name__ == "__main__":
    zen(train, pre_call=process_config).hydra_main(config_name="base", version_base="1.2", config_path=None)
````

New config file
```python
cs = ConfigStore.instance()
cs.store(group="datamodule", name="vo", node=VODataModuleCfg)
cs.store(group="datamodule", name="regular", node=DataModuleCfg)

cs.store(name="contrastive", node=TrainCfg, package="_global_")
cs.store(group="mode", name="debug", node=TrainCfg)
```
Where `TrainCfg` takes in a `datamodule` argument (and later a model as well).

new `main.py` which depends on the **new** config file.
```python
...
if __name__ == "__main__":
    zen(train, pre_call=process_config).hydra_main(config_name="base", version_base="1.2", config_path=None)
```

The datamodule and model arguments defined in the original config are not compatible with the new ones.

Would it be possible to seperate the 2 config by using a different `config_name`? Such that if we set `config_name="contrastive"` only the config option defined there are available?

**Comment by thomassajot** [comment]
I finally understood the issue and `cs.add_to_hydra_store()` is the catch indeed!

The problem was that the current code uses a mixture of Hydra zen and (vanilla) Hydra to instantiate the config. Replacing the instantiation by `hydra_zen.ZenStore` allows to populate Hydra's config within `if __name__ == "__main__":`. 

The updates main.py now look like

**main1.py**
```python 
from config1 import my_store

if __name__ == "__main__":
    my_store.add_to_hydra_store()
    zen(train, pre_call=process_config).hydra_main(config_name="base", version_base="1.2", config_path=None)
```


**main2.py**
```python 
from config2 import my_store

if __name__ == "__main__":
    my_store.add_to_hydra_store()
    zen(train, pre_call=process_config).hydra_main(config_name="base", version_base="1.2", config_path=None)
```

**Comment by rsokl** [comment]
> The problem was that the current code uses a mixture of Hydra zen and (vanilla) Hydra to instantiate the config. Replacing the instantiation by hydra_zen.ZenStore allows to populate Hydra's config within if __name__ == "__main__":.

Yep, this is exactly right! Perhaps I should add a brief How-To in our docs to convey this; although the pattern is already common in our dos.

**Comment by thomassajot** [comment]
It would be great to make this clearer as I did not find this clear in the docs.
