### ISSUE TITLE
build function with `populate_full_signature=True` does not recognize the signature for a subclass of `pydantic.BaseModel`

### ISSUE THREAD

**Issue by glebrh** [mit-ll-responsible-ai/hydra-zen#585]
System info:
**OS**: Mac M1 14.1.1
**python**: 3.9.16 (also tested with 3.12.0 - same result)
**hydra-zen**: 0.11.0
**pydantic**: 1.10.13  (also tested with 2.4.2)

Hi,

First of all - big kudos to all the contributors for creating such a helpful package!
I bumped into the issue with `pydantic.BaseModel` while using `build(..., populate_full_signature=True`): it is neither able to populate the whole signature of the target and also does not throw `ValueError` with ".... does not have an inspectable signature.".
Essentially the example is pretty simple:

```python
from pydantic import BaseModel
from hydra_zen import builds, to_yaml

class A(BaseModel):
    a: str
    b: int = 1

built_conf = builds(A, populate_full_signature=True)
print(to_yaml(built_conf))
```

Which will output:

```yaml
_target_: __main__.A
```

On the other hand, while using pydantic.dataclasses it works like a charm (which is expected, since these are compatible with built-in dataclasses)

```python
from pydantic import dataclasses
from hydra_zen import builds, to_yaml

@dataclasses.dataclass
class B:
    a: str
    b: int = 1

built_conf = builds(B, populate_full_signature=True)
print(to_yaml(built_conf))
```

will give use:

```yaml
_target_: __main__.B
a: ???
b: 1
```

I could only guess, but it seems to be related [to this branch with logic](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/03e45086c5023fda4028291e885eb85b78d28b1e/src/hydra_zen/structured_configs/_implementations.py#L2398)

Not sure whether this is a bug :) and should it be addressed with `hydra-zen`, but I would appreciate any feedback.

**Comment by rsokl** [comment]
Thanks for the report and for isolating the branch logic - that is indeed the culprit! My first attempt at a fix seems to work; I'll add some tests and will include this in the next release of hydra-zen. I'll note, however, that I have not had the resources for maintaining pydantic support, especially with their release of v2.0, so I can't promise that all wrinkles will be ironed out.
