### ISSUE TITLE
`hydra_convert` not respected for `builds`

### ISSUE THREAD

**Issue by petosa** [mit-ll-responsible-ai/hydra-zen#592]
I am running into unexpected behavior with the `hydra_convert` parameter in my config.

```python
import dataclasses
from hydra_zen import instantiate, builds, make_config

@dataclasses.dataclass
class A:
    number: int

res = (
    instantiate(
        builds(A, number=1, hydra_convert="all")
    )
)
print(type(res))
```

I would expect this code to print `<class 'dict'>` but instead it prints `<class '__main__.A'>`. This indicates that the `hydra_convert` parameter is not being respected (since the `builds` is not converted to a `dict`). Is there someway to have `instantiate` respect `hydra_convert` here?

The same code works fine for `make_config`.
```python
res = (
    instantiate(
        make_config(A=1, hydra_convert="all")
    )
)
print(type(res))
```
prints `<class 'dict'>`.

**Comment by petosa** [comment]
I also have a broader question - why doesn't hydra-zen convert the top-level config with `instantiate`?

```
from dataclasses import dataclass
from hydra_zen import instantiate
from omegaconf import OmegaConf

@dataclass
class Foo:
    a: int = 123

class MyTarget:
    def __init__(self, foo, bar):
        self.foo = foo
        self.bar = bar

cfg = OmegaConf.create(
    {
        "_target_": "__main__.MyTarget",
        "foo": Foo(),
        "bar": {"b": 456},
    }
)

obj_all = instantiate(cfg, _convert_="all")
assert isinstance(obj_all, dict)
```

The assertion fails as the type of `obj_all` is `MyTarget`.

**Comment by rsokl** [comment]
`hydra_zen.instantiate` is merely an alias for `hydra.utils.instantiate` with some hydra-zen-specific type overloads added to it. All of the behaviors that you are asking about come down to "quirks" of Hydra's implementation. E.g.

```python
from hydra.utils import instantiate
import dataclasses


@dataclasses.dataclass
class A:
    number: int
    _target_:str = '__main__.A'
    _convert_: str = "all"


res = instantiate(A, number=1)

print(type(res))
```
```
<class '__main__.A'>
```

I'm not sure why it is implemented this way :/

**Comment by petosa** [comment]
I see, would you recommend I cross-post on hyda's issues? This unintuitive behavior is messing up my configs. Alternatively, any good workaround? I suppose I can convert the builds to a dictconfig somehow.

**Comment by rsokl** [comment]
You might open this as an issue on Hydra, but I think there is not much chance that this will be changed. I think that the project is only being maintained by a skeleton crew at this point. You could always wrap the version of `instantiate` that you are using so that it includes the conversion logic that you are looking for.

**Comment by petosa** [comment]
Thanks @rsokl. It seems like hydra-zen still sees active development, what is the longer-term plan? To keep building on top of hydra even though it's stagnating?

**Comment by rsokl** [comment]
My expectation is that Hydra will continue to be maintained such that it remains usable as the core of hydra-zen. I may lend a hand with some basic maintenance if need be, but I hope to not have to.

Otherwise, I plan on continuing to add features and polish to hydra-zen. v0.12 will be one of our biggest updates in recent history. 😁
