### ISSUE TITLE
How to retrieve the complete current hydra config? 

### ISSUE THREAD

**Issue by danielgafni** [mit-ll-responsible-ai/hydra-zen#611]
Hey everyone! 

Maybe this sounds like a stupid question, but I was not able to find a straightforward way of doing this (both in `hydra` and `hydra-zen` docs). 

I am trying out something like:

```python
cs = ConfigStore.instance()
cfg = OmegaConf.create(cs.load("fit.yaml").node)
```

but this is just the default config without current overrides. 

Thanks a lot for the help!

P.S. callbacks won't work as I need it inside my actual script

**Comment by rsokl** [comment]
Does this address what you are trying to do? https://mit-ll-responsible-ai.github.io/hydra-zen/tutorials/basic_app.html#inspecting-the-results

**Comment by danielgafni** [comment]
Hey, thanks! 

This still looks like a good workaround. I think it should be sufficient for me.

However, I think there should be a less hacky way of doing this (for example, this won't work if output dir creation is disabled). So I'm going to keep this issue opened.

**Comment by rsokl** [comment]
https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.zen.html#hydra_zen.zen see the section "Passing Through The Full Input Config" ?

**Comment by danielgafni** [comment]
Yep this is great! Thanks!
