### ISSUE TITLE
How to do config composition?

### ISSUE THREAD

**Issue by thomassajot** [mit-ll-responsible-ai/hydra-zen#660]
I have been stuck on trying to update a predefined config object with another one which defines a subset of the arguments.
Could someone share an example of how to compose/merge two configs ?

**Comment by rsokl** [comment]
https://github.com/mit-ll-responsible-ai/hydra-zen/discussions/472#discussioncomment-5825824

**Comment by thomassajot** [comment]
@rsokl, sorry I did not mention it in my question. How to do the merge in the cli?

**Comment by rsokl** [comment]
Check the Hydra documentation for CLI grammar/capabilities.
