### ISSUE TITLE
_target_ for inner classes is incorrect

### ISSUE THREAD

**Issue by lebrice** [mit-ll-responsible-ai/hydra-zen#705]
Hello there, big fan of this package.

I believe that there is a bug with the `safe_name` function, that causes the `_target_` field of dynamic configs to be wrong if the target is an inner class:

```python
# project.configs.algorithm.__init__.py

import hydra_zen
import dataclasses

class MyAlgorithm:
    @dataclasses.dataclass
    class HParams:
        lr: float = 0.01



HparamsConfig = hydra_zen.builds(MyAlgorithm.HParams)
config = HparamsConfig()

# This should be true, but it isn't! The target is actually "project.configs.algorithm.HParams"!
assert config._target_ == "project.configs.algorithm.MyAlgorithm.HParams"
```

**Comment by lebrice** [comment]
here's my current work-around:

```python
def patched_safe_name(obj: Any, repr_allowed: bool = False):
    if not hasattr(obj, "__qualname__"):
        return safe_name(obj, repr_allowed=repr_allowed)

    name = safe_name(obj)
    qualname = obj.__qualname__
    assert isinstance(qualname, str)

    if name != qualname and qualname.endswith("." + name):
        return qualname

    return name
```

**Comment by rsokl** [comment]
Thanks for the report! I'll take a look at this and will release a patch if I can get this working without breaking compatibility elsewhere.

**Comment by rsokl** [comment]
Unfortunately it looks like your workaround breaks support for a bunch of things in the `random` namespace (and probably other packages/patterns). I'll have to take some time to think of a more robust fix.

**Comment by rsokl** [comment]
oh actually maybe there is an easy fix. Let's see if CI passes: https://github.com/mit-ll-responsible-ai/hydra-zen/pull/708

**Comment by rsokl** [comment]
Just published a pre-release candidate with a fix for this: https://mit-ll-responsible-ai.github.io/hydra-zen/changes.html#rc1-2024-07-13

Give it a spin and please let me know if anything breaks for you
