### ISSUE TITLE
New feature: `hydra_zen.from_yaml`

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#89]
`hydra_zen.from_yaml` would take in a yaml-string and returns a corresponding structured config (dataclass object).

Why is this useful? The case that I encountered is wanting to load and inherit from a config:

```python
# just an example

# not a dataclass object (not inheritable)
LoadedConf = OmegaConf.load(exp_dir / ".hydra/config.yaml")

# now a dataclass object (all annotations will be `Any`)
LoadedConf = hydra_zen.from_yaml(LoadedConf)

ModifiedConf = builds(Trainer, gpus=1, accelerator=None, batch_size=25, builds_bases=(LoadedConf ,))
```

I realize that LoadedConf can have its attributes be updated directly, and that there are probably mechanisms provided by hydra/omegaconf to merge configs, but thus far we do not expect our users to use any variety of config other than a structured config dataclass. Nor do we expect them to be well-versed in omegaconf. Thus it seems like enabling this inheritance route is natural / elegant.

I would be interested to get feedback on this. 
- Is the above workflow something we want to recommend or is it simpler/cleaner to update the attributes directly (or, to leverage hydra/omegaconf)?
- Are there any downsides/limitations to the above workflow?
- Unanticipated hurdles to going from yaml to dataclass?

**Comment by jgbos** [comment]
How is this different then `hydra_zen.load_from_yaml`?

**Comment by rsokl** [comment]
`load_from_yaml` produces a omegaconf container (I can't remember which one), so the loaded config cannot be used in places like `builds_bases` where a dataclass object is needed.

Maybe the function should just be `to_dataclass`, and it can convert any targeted structured config to a dataclass.

**Comment by jgbos** [comment]
Ah yeah.  I think it will be confusing to have `load_from_yaml` and `from_yaml`.  Since hydra-zen works on dataclasses, should we avoid having functions output an omegaconf container?  In that case should `load_from_yaml` return a dataclass.  Is there any reason to expose omegaconf containers to the user?

**Comment by rsokl** [comment]
> Since hydra-zen works on dataclasses, should we avoid having functions output an omegaconf container?

I have been mulling this over. There are clearly some enhancements that are enabled by using omegaconf containers (although I don't think that I leverage them all that much). 

One option is: wherever we require a true dataclass (e.g. in `builds_bases`) we automatically convert any omegaconf container to a dataclass. This way users can operate with omegaconf containers if they'd like, but then those containers interface seamlessly with hydra-zen's utils.

**Comment by jgbos** [comment]
Yeah I don't use the omegaconf containers and I've always felt they are a pain to deal with.

I think I like the option of allowing `builds_bases` take in omegaconf containers though rather than add another function.

**Comment by rsokl** [comment]
> I think I like the option of allowing builds_bases take in omegaconf containers though rather than add another function.

Agreed. Closing this with preference for this new direction
