### ISSUE TITLE
New feature: `hydra_zen.get_target`

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#92]
`hydra_zen.get_target` would enable users to access (and import) the target of a config.

```python
>>> Conf = builds(dict)
>>> get_target(Conf)
<class 'dict'>
```

This is useful for things like loading a lightning module from a checkpoint, via a hydra yaml.

```python
>>> ExpConfig = load_from_yaml("my_exp.yaml")
>>> LitModule = get_target(ExpConfig.lit_module)  # get lightning module class
>>> module_kwargs = instantiate(builds(dict, builds_bases=(ExpConfig.lit_module,))) 
>>> LitModule.load_from_checkpoint(checkpoint_path="./chk.ckpt, **module_kwargs)
```

Without `get_target`, one would need to do

```python
>>> LitModule = type(instantiate(ExpConfig.lit_module))
```
which is a bit wasteful, since you have to initialize the whole module just to get the type.

I can imaging that `get_target` could be handy in simpler cases as well.

**Comment by jgbos** [comment]
This looks interesting and useful.  I honestly have never done something like this, but now that I know I will probably use it more.
