### ISSUE TITLE
PEP 561 compatibility

### ISSUE THREAD

**Issue by Jasha10** [mit-ll-responsible-ai/hydra-zen#96]
Hi,

Would it be possible to make hydra-zen compliant with [PEP 561](https://www.python.org/dev/peps/pep-0561) by distributing a `py.typed` file with the package?

Currently I'm getting `Skipping analyzing "hydra_zen": found module but no type hints or library stubs` when I run mypy on a test file. Here are steps to reproduce this error:
```text
$ pip install hydra-zen mypy
...
Successfully installed PyYAML-5.4.1 antlr4-python3-runtime-4.8 hydra-core-1.1.1 hydra-zen-0.2.0 mypy-0.910 mypy-extensions-0.4.3 omegaconf-2.1.1 toml-0.10.2 typing-extensions-3.10.0.2
...
$ echo "from hydra_zen import builds" > tmp.py
$ mypy tmp.py
tmp.py:1: error: Skipping analyzing "hydra_zen": found module but no type hints or library stubs
tmp.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

I believe that adding an empty `py.typed` file to the `src/hydra_zen` directory (and modifying `setup.py` so that the `py.typed` file is distributed with the `hydra-zen` package) would make it possible for type checkers following PEP 561 to discover the type hints in `src`.
(I'd be happy to submit a PR to this effect.)

**Comment by rsokl** [comment]
Thanks for bringing this to my attention. It was funny timing - I had just been looking at that PEP. See #97, where I address this. I plan to release `0.3.0` after this, so the pypi package will be mypy-compatible soon.

**Comment by rsokl** [comment]
@Jasha10 `v0.3.0rc1` has been [released on pypi](https://pypi.org/project/hydra-zen/0.3.0rc1/).
